use std::{
    collections::{BTreeMap, BTreeSet},
    str::FromStr,
};

use proc_macro2::Ident;
use syn::{parse_quote, Fields, ItemTrait};

#[derive(Default)]
pub struct DispatchMap(pub BTreeMap<Dispatchable<ItemTrait>, BTreeSet<Dispatchalor>>);

pub struct Dispatchable<T>(T);

/// For each <Dispatchable> -> <{ position, ident, fields }>
/// Used for dispatching
pub enum Position {
    /// The index of the field being dispatched
    Index(usize),

    /// The key of the field being dispatched
    Key(String),
}

/// This one is important. Use fields and position to create a pattern.
/// e.g. ident + position + fields + "bound signature" = `Ident::(_, X, ..) => X.method_call(<args if any>)`
pub struct Dispatchalor {
    /// The name of the variant
    pub ident: Ident,

    /// Used for dispatching
    pub position: Position,

    /// Wowawiwa
    pub fields: Fields,
}

pub enum Std {
    Any,
    Borrow,
    BorrowMut,
    Eq,
    AsMut,
    AsRef,
    From,
    Into,
    TryFrom,
    TryInto,
    Default,
    Binary,
    Debug,
    Display,
    LowerExp,
    LowerHex,
    Octal,
    Pointer,
    UpperExp,
    UpperHex,
    Future,
    IntoFuture,
    FromIterator,
    FusedIterator,
    IntoIterator,
    Product,
    Sum,
    Copy,
    Sized,
    ToSocketAddrs,
    Add,
    AddAssign,
    BitAnd,
    BitAndAssign,
    BitOr,
    BitOrAssign,
    BitXor,
    BitXorAssign,
    Deref,
    DerefMut,
    Div,
    DivAssign,
    Drop,
    Fn,
    FnMut,
    FnOnce,
    Index,
    IndexMut,
    Mul,
    MulAssign,
    Neg,
    Not,
    Rem,
    RemAssign,
    Shl,
    ShlAssign,
    Shr,
    ShrAssign,
    Sub,
    SubAssign,
    Termination,
    SliceIndex,
    FromStr,
    ToString,
}

impl From<Std> for Dispatchable<ItemTrait> {
    fn from(value: Std) -> Self {
        Dispatchable(match value {
            Std::Any => parse_quote!(include!("./std/Any.rs")),
            Std::Borrow => parse_quote!(include!("./std/Borrow.rs")),
            Std::BorrowMut => parse_quote!(include!("./std/BorrowMut.rs")),
            Std::Eq => parse_quote!(include!("./std/Eq.rs")),
            Std::AsMut => parse_quote!(include!("./std/AsMut.rs")),
            Std::AsRef => parse_quote!(include!("./std/AsRef.rs")),
            Std::From => parse_quote!(include!("./std/From.rs")),
            Std::Into => parse_quote!(include!("./std/Into.rs")),
            Std::TryFrom => parse_quote!(include!("./std/TryFrom.rs")),
            Std::TryInto => parse_quote!(include!("./std/TryInto.rs")),
            Std::Default => parse_quote!(include!("./std/Default.rs")),
            Std::Binary => parse_quote!(include!("./std/Binary.rs")),
            Std::Debug => parse_quote!(include!("./std/Debug.rs")),
            Std::Display => parse_quote!(include!("./std/Display.rs")),
            Std::LowerExp => parse_quote!(include!("./std/LowerExp.rs")),
            Std::LowerHex => parse_quote!(include!("./std/LowerHex.rs")),
            Std::Octal => parse_quote!(include!("./std/Octal.rs")),
            Std::Pointer => parse_quote!(include!("./std/Pointer.rs")),
            Std::UpperExp => parse_quote!(include!("./std/UpperExp.rs")),
            Std::UpperHex => parse_quote!(include!("./std/UpperHex.rs")),
            Std::Future => parse_quote!(include!("./std/Future.rs")),
            Std::IntoFuture => parse_quote!(include!("./std/IntoFuture.rs")),
            Std::FromIterator => parse_quote!(include!("./std/FromIterator.rs")),
            Std::FusedIterator => parse_quote!(include!("./std/FusedIterator.rs")),
            Std::IntoIterator => parse_quote!(include!("./std/IntoIterator.rs")),
            Std::Product => parse_quote!(include!("./std/Product.rs")),
            Std::Sum => parse_quote!(include!("./std/Sum.rs")),
            Std::Copy => parse_quote!(include!("./std/Copy.rs")),
            Std::Sized => parse_quote!(include!("./std/Sized.rs")),
            Std::ToSocketAddrs => parse_quote!(include!("./std/ToSocketAddrs.rs")),
            Std::Add => parse_quote!(include!("./std/Add.rs")),
            Std::AddAssign => parse_quote!(include!("./std/AddAssign.rs")),
            Std::BitAnd => parse_quote!(include!("./std/BitAnd.rs")),
            Std::BitAndAssign => parse_quote!(include!("./std/BitAndAssign.rs")),
            Std::BitOr => parse_quote!(include!("./std/BitOr.rs")),
            Std::BitOrAssign => parse_quote!(include!("./std/BitOrAssign.rs")),
            Std::BitXor => parse_quote!(include!("./std/BitXor.rs")),
            Std::BitXorAssign => parse_quote!(include!("./std/BitXorAssign.rs")),
            Std::Deref => parse_quote!(include!("./std/Deref.rs")),
            Std::DerefMut => parse_quote!(include!("./std/DerefMut.rs")),
            Std::Div => parse_quote!(include!("./std/Div.rs")),
            Std::DivAssign => parse_quote!(include!("./std/DivAssign.rs")),
            Std::Drop => parse_quote!(include!("./std/Drop.rs")),
            Std::Fn => parse_quote!(include!("./std/Fn.rs")),
            Std::FnMut => parse_quote!(include!("./std/FnMut.rs")),
            Std::FnOnce => parse_quote!(include!("./std/FnOnce.rs")),
            Std::Index => parse_quote!(include!("./std/Index.rs")),
            Std::IndexMut => parse_quote!(include!("./std/IndexMut.rs")),
            Std::Mul => parse_quote!(include!("./std/Mul.rs")),
            Std::MulAssign => parse_quote!(include!("./std/MulAssign.rs")),
            Std::Neg => parse_quote!(include!("./std/Neg.rs")),
            Std::Not => parse_quote!(include!("./std/Not.rs")),
            Std::Rem => parse_quote!(include!("./std/Rem.rs")),
            Std::RemAssign => parse_quote!(include!("./std/RemAssign.rs")),
            Std::Shl => parse_quote!(include!("./std/Shl.rs")),
            Std::ShlAssign => parse_quote!(include!("./std/ShlAssign.rs")),
            Std::Shr => parse_quote!(include!("./std/Shr.rs")),
            Std::ShrAssign => parse_quote!(include!("./std/ShrAssign.rs")),
            Std::Sub => parse_quote!(include!("./std/Sub.rs")),
            Std::SubAssign => parse_quote!(include!("./std/SubAssign.rs")),
            Std::Termination => parse_quote!(include!("./std/Termination.rs")),
            Std::SliceIndex => parse_quote!(include!("./std/SliceIndex.rs")),
            Std::FromStr => parse_quote!(include!("./std/FromStr.rs")),
            Std::ToString => parse_quote!(include!("./std/ToString.rs")),
        })
    }
}

impl FromStr for Std {
    type Err = ();
    fn from_str(value: &str) -> Result<Self, ()> {
        Ok(match value {
            "Any" => Self::Any,
            "Borrow" => Self::Borrow,
            "BorrowMut" => Self::BorrowMut,
            "Eq" => Self::Eq,
            "AsMut" => Self::AsMut,
            "AsRef" => Self::AsRef,
            "From" => Self::From,
            "Into" => Self::Into,
            "TryFrom" => Self::TryFrom,
            "TryInto" => Self::TryInto,
            "Default" => Self::Default,
            "Binary" => Self::Binary,
            "Debug" => Self::Debug,
            "Display" => Self::Display,
            "LowerExp" => Self::LowerExp,
            "LowerHex" => Self::LowerHex,
            "Octal" => Self::Octal,
            "Pointer" => Self::Pointer,
            "UpperExp" => Self::UpperExp,
            "UpperHex" => Self::UpperHex,
            "Future" => Self::Future,
            "IntoFuture" => Self::IntoFuture,
            "FromIterator" => Self::FromIterator,
            "FusedIterator" => Self::FusedIterator,
            "IntoIterator" => Self::IntoIterator,
            "Product" => Self::Product,
            "Sum" => Self::Sum,
            "Copy" => Self::Copy,
            "Sized" => Self::Sized,
            "ToSocketAddrs" => Self::ToSocketAddrs,
            "Add" => Self::Add,
            "AddAssign" => Self::AddAssign,
            "BitAnd" => Self::BitAnd,
            "BitAndAssign" => Self::BitAndAssign,
            "BitOr" => Self::BitOr,
            "BitOrAssign" => Self::BitOrAssign,
            "BitXor" => Self::BitXor,
            "BitXorAssign" => Self::BitXorAssign,
            "Deref" => Self::Deref,
            "DerefMut" => Self::DerefMut,
            "Div" => Self::Div,
            "DivAssign" => Self::DivAssign,
            "Drop" => Self::Drop,
            "Fn" => Self::Fn,
            "FnMut" => Self::FnMut,
            "FnOnce" => Self::FnOnce,
            "Index" => Self::Index,
            "IndexMut" => Self::IndexMut,
            "Mul" => Self::Mul,
            "MulAssign" => Self::MulAssign,
            "Neg" => Self::Neg,
            "Not" => Self::Not,
            "Rem" => Self::Rem,
            "RemAssign" => Self::RemAssign,
            "Shl" => Self::Shl,
            "ShlAssign" => Self::ShlAssign,
            "Shr" => Self::Shr,
            "ShrAssign" => Self::ShrAssign,
            "Sub" => Self::Sub,
            "SubAssign" => Self::SubAssign,
            "Termination" => Self::Termination,
            "SliceIndex" => Self::SliceIndex,
            "FromStr" => Self::FromStr,
            "ToString" => Self::ToString,
        })
    }
}
